spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lushopai/service-configuration
          clone-on-start: true
          search-paths: service-configuration



server:
  port: 8888
